import asyncio
import logging
import os
import subprocess
from abc import ABC, abstractmethod
from typing import TYPE_CHECKING, Optional

from gh_nexus.models import ProjectGoal, Task, TaskPriority, TaskResult, Worker

if TYPE_CHECKING:
    from gh_nexus.github import GitHubProject

logger = logging.getLogger(__name__)


class BaseRole(ABC):
    name: str = ""
    description: str = ""

    @abstractmethod
    async def execute(self, context: dict) -> dict:
        pass


class Visionary(BaseRole):
    name = "Visionary"
    description = "Define project goals & direction - Requirements understanding, goal breakdown"

    def __init__(self, github: Optional["GitHubProject"] = None):
        self.github = github

    async def execute(self, context: dict) -> dict:
        user_requirements = context.get("requirements", "")
        
        if not user_requirements:
            user_requirements = self._get_default_vision()
        
        goals = self._decompose_goals(user_requirements)
        
        if self.github and context.get("auto_create_issues", False):
            await self._create_github_issues(goals)
        
        return {
            "goals": [goal.model_dump() for goal in goals],
            "strategy": self._define_strategy(goals),
        }

    def _get_default_vision(self) -> str:
        return """
# Gh Nexus - AI Agent Project Orchestration System

## Vision
Build an autonomous AI agent development platform centered around GitHub Projects, where creating issues automatically triggers AI agents to implement solutions.

## Core Features
1. GitHub Integration - Use gh CLI for all project operations
2. Agent Workers - Register and manage coding agents (opencode, claude-code, cursor)
3. Docker Development - Containerized development environment
4. Automation Pipeline - Issue → Agent → PR workflow
5. Multi-Agent Collaboration - Visionary, Overseer, Interpreter, Dispatcher, Worker, Tester, Rewarder

## Technical Goals
- Webhook server for real-time GitHub events
- Git worktree management for isolated agent workspaces
- Auto PR creation after agent completes
- CI/CD integration with GitHub Actions
- User authentication system
- RESTful API for external integrations

## Future Enhancements
- Multi-repo support
- Agent learning from feedback
- Advanced scheduling and prioritization
- Analytics and reporting dashboard
"""

    async def _create_github_issues(self, goals: list[ProjectGoal]) -> None:
        if not self.github:
            return
        
        logger.info(f"Creating {len(goals)} GitHub issues...")
        
        for goal in goals:
            issue_body = f"""
## Vision

{goal.description}

## Status
- **Status**: {goal.status}
- **Progress**: {goal.progress * 100:.0f}%
{f'- **Target Date**: {goal.target_date}' if goal.target_date else ''}

---
*Generated by Gh Nexus Visionary*
"""
            await self.github.create_issue(
                title=goal.title,
                body=issue_body,
                labels=["visionary", "goal"],
            )
        
        logger.info(f"Created {len(goals)} GitHub issues")

    def _decompose_goals(self, requirements: str) -> list[ProjectGoal]:
        goals = []
        lines = requirements.split("\n")
        
        current_goal = None
        current_section = "General"
        
        for line in lines:
            line = line.strip()
            if not line:
                continue
            
            if line.startswith("# "):
                current_section = line.lstrip("# ").strip()
            elif line.startswith("## "):
                section_name = line.lstrip("## ").strip()
                current_goal = ProjectGoal(
                    title=section_name,
                    description="",
                    status="active",
                )
            elif line.startswith(("- ", "* ")) and any(keyword in line.lower() for keyword in ["feature", "goal", "enhancement", "integration", "support", "system"]):
                item = line.lstrip("-* ").strip()
                if current_goal:
                    current_goal.description += f"- {item}\n"
                else:
                    goals.append(ProjectGoal(
                        title=item,
                        description=f"Part of: {current_section}",
                        status="active",
                    ))
            elif line[0:1].isdigit() and ". " in line:
                item = line.split(". ", 1)[1] if ". " in line else line
                goals.append(ProjectGoal(
                    title=item,
                    description=f"Part of: {current_section}",
                    status="active",
                ))
            elif current_goal:
                if len(line) > 2:
                    current_goal.description += line + "\n"
        
        if current_goal and current_goal.title:
            goals.append(current_goal)
        
        if not goals:
            goals.append(ProjectGoal(
                title="Project Implementation",
                description=requirements[:500],
                status="active",
            ))
        
        logger.info(f"Visionary created {len(goals)} goals")
        return goals

    def _define_strategy(self, goals: list[ProjectGoal]) -> str:
        phases = []
        
        for i, goal in enumerate(goals):
            phases.append(f"Phase {i+1}: {goal.title}")
        
        return "\n".join(phases)


class Overseer(BaseRole):
    name = "Overseer"
    description = "Monitor progress, assess risks - Progress tracking, risk alerting"

    async def execute(self, context: dict) -> dict:
        tasks = context.get("tasks", [])
        workers = context.get("workers", [])
        
        progress = self._calculate_progress(tasks)
        risks = self._identify_risks(tasks, workers)
        
        return {
            "progress": progress,
            "risks": risks,
            "alerts": self._generate_alerts(risks),
            "metrics": self._collect_metrics(tasks, workers),
        }

    def _calculate_progress(self, tasks: list[Task]) -> float:
        if not tasks:
            return 0.0
        
        completed = sum(1 for t in tasks if t.status.value == "Done")
        return (completed / len(tasks)) * 100

    def _identify_risks(self, tasks: list[Task], workers: list[Worker]) -> list[dict]:
        risks = []
        
        blocked = [t for t in tasks if t.status.value == "Blocked"]
        if blocked:
            risks.append({
                "type": "blocked_tasks",
                "severity": "high",
                "count": len(blocked),
                "message": f"{len(blocked)} tasks are blocked",
            })
        
        idle_workers = [w for w in workers if w.is_available and w.status == "idle"]
        if idle_workers and len(tasks) > len(workers):
            risks.append({
                "type": "resource_mismatch",
                "severity": "medium",
                "message": f"{len(idle_workers)} workers idle but tasks pending",
            })
        
        overdue = [t for t in tasks if t.actual_hours > t.estimated_hours * 1.5]
        if overdue:
            risks.append({
                "type": "overdue_tasks",
                "severity": "medium",
                "count": len(overdue),
                "message": f"{len(overdue)} tasks exceeding estimates",
            })
        
        return risks

    def _generate_alerts(self, risks: list[dict]) -> list[str]:
        alerts = []
        for risk in risks:
            if risk.get("severity") == "high":
                alerts.append(f"ALERT: {risk['message']}")
            elif risk.get("severity") == "medium":
                alerts.append(f"WARNING: {risk['message']}")
        return alerts

    def _collect_metrics(self, tasks: list[Task], workers: list[Worker]) -> dict:
        return {
            "total_tasks": len(tasks),
            "completed_tasks": len([t for t in tasks if t.status.value == "Done"]),
            "in_progress": len([t for t in tasks if t.status.value == "In Progress"]),
            "blocked_tasks": len([t for t in tasks if t.status.value == "Blocked"]),
            "total_workers": len(workers),
            "active_workers": len([w for w in workers if w.status != "idle"]),
        }


class Interpreter(BaseRole):
    name = "Interpreter"
    description = "Analyze requirements, decompose tasks - Requirements analysis, task breakdown"

    async def execute(self, context: dict) -> dict:
        goals = context.get("goals", [])
        
        tasks = []
        for goal in goals:
            goal_tasks = self._decompose_goal(goal)
            tasks.extend(goal_tasks)
        
        return {
            "tasks": [t.model_dump() for t in tasks],
            "task_count": len(tasks),
            "complexity_analysis": self._analyze_complexity(tasks),
        }

    def _decompose_goal(self, goal: ProjectGoal) -> list[Task]:
        tasks = []
        title_lower = goal.title.lower()
        desc_lower = goal.description.lower()
        
        main_task = Task(
            title=f"Implement: {goal.title}",
            description=goal.description,
            priority=TaskPriority.MEDIUM,
            estimated_hours=2.0,
        )
        tasks.append(main_task)
        
        task_keywords = {
            "webhook": [
                ("[Webhook] Create endpoint handler", "Implement HTTP webhook endpoint"),
                ("[Webhook] Add signature verification", "Add GitHub webhook signature verification"),
                ("[Webhook] Setup event routing", "Route events to appropriate handlers"),
            ],
            "server": [
                ("[Server] Create HTTP server", "Create HTTP server with aiohttp"),
                ("[Server] Add request validation", "Validate incoming requests"),
                ("[Server] Setup logging", "Add structured logging"),
            ],
            "docker": [
                ("[Docker] Create Dockerfile", "Create production Dockerfile"),
                ("[Docker] Add docker-compose", "Add docker-compose for development"),
                ("[Docker] Setup multi-stage build", "Optimize image size"),
            ],
            "deploy": [
                ("[Deploy] Setup CI/CD", "Configure GitHub Actions"),
                ("[Deploy] Add health checks", "Add health check endpoints"),
                ("[Deploy] Setup monitoring", "Add metrics and logging"),
            ],
            "test": [
                ("[Test] Write unit tests", "Create unit tests for core functions"),
                ("[Test] Add integration tests", "Create integration tests"),
                ("[Test] Setup test coverage", "Configure coverage reporting"),
            ],
            "api": [
                ("[API] Design API schema", "Design OpenAPI schema"),
                ("[API] Implement endpoints", "Implement REST endpoints"),
                ("[API] Add authentication", "Add API authentication"),
            ],
            "agent": [
                ("[Agent] Create agent interface", "Define agent protocol interface"),
                ("[Agent] Implement worker pool", "Create worker pool management"),
                ("[Agent] Add task queue", "Implement async task queue"),
            ],
            "worktree": [
                ("[Worktree] Create worktree manager", "Implement git worktree creation"),
                ("[Worktree] Add cleanup logic", "Implement automatic cleanup"),
                ("[Worktree] Add branch management", "Manage feature branches"),
            ],
            "pr": [
                ("[PR] Create PR automation", "Implement auto PR creation"),
                ("[PR] Add PR description", "Generate PR description"),
                ("[PR] Setup PR checks", "Add required status checks"),
            ],
            "automation": [
                ("[Automation] Create workflow engine", "Implement automation workflow"),
                ("[Automation] Add event handlers", "Handle GitHub events"),
                ("[Automation] Setup notifications", "Add result notifications"),
            ],
        }
        
        for keyword, subtasks in task_keywords.items():
            if keyword in title_lower or keyword in desc_lower:
                for subtask_title, subtask_desc in subtasks:
                    tasks.append(Task(
                        title=subtask_title,
                        description=subtask_desc,
                        parent_id=main_task.id,
                        priority=TaskPriority.LOW,
                        estimated_hours=1.0,
                    ))
        
        if len(tasks) == 1:
            tasks.append(Task(
                title=f"[{goal.title}] Write tests",
                description="Write unit and integration tests",
                parent_id=main_task.id,
                priority=TaskPriority.LOW,
                estimated_hours=1.0,
            ))
            tasks.append(Task(
                title=f"[{goal.title}] Update documentation",
                description="Update README and documentation",
                parent_id=main_task.id,
                priority=TaskPriority.LOW,
                estimated_hours=0.5,
            ))
        
        logger.info(f"Interpreter decomposed goal '{goal.title}' into {len(tasks)} tasks")
        return tasks

    def _analyze_complexity(self, tasks: list[Task]) -> dict:
        return {
            "estimated_hours": sum(t.estimated_hours for t in tasks),
            "parallel_possible": len(tasks),
            "critical_path": len(tasks) // 2,
        }


class Dispatcher(BaseRole):
    name = "Dispatcher"
    description = "Assign tasks to workers - Task dispatch, load balancing"

    async def execute(self, context: dict) -> dict:
        tasks = context.get("tasks", [])
        workers = context.get("workers", [])
        
        assignments = self._assign_tasks(tasks, workers)
        
        return {
            "assignments": assignments,
            "load_distribution": self._calculate_load(workers, assignments),
        }

    def _assign_tasks(self, tasks: list[Task], workers: list[Worker]) -> list[dict]:
        assignments = []
        available_workers = [w for w in workers if w.is_available]
        
        for i, task in enumerate(tasks):
            if i >= len(available_workers):
                i = i % len(available_workers) if available_workers else -1
            
            if i >= 0:
                worker = available_workers[i]
                assignments.append({
                    "task_id": str(task.id),
                    "worker_id": str(worker.id),
                    "worker_name": worker.name,
                })
                task.assign_worker(worker.id)
                worker.current_task_id = task.id
                worker.status = "working"
        
        return assignments

    def _calculate_load(self, workers: list[Worker], assignments: list[dict]) -> dict:
        worker_load = {}
        for assignment in assignments:
            wid = assignment["worker_id"]
            worker_load[wid] = worker_load.get(wid, 0) + 1
        
        return {
            "distribution": worker_load,
            "balanced": max(worker_load.values()) - min(worker_load.values()) <= 1 if worker_load else True,
        }


class WorkerRole(BaseRole):
    name = "Worker"
    description = "Execute code tasks - Code generation, file operations"

    def __init__(self, worker: Worker, workdir: str = "."):
        self.worker = worker
        self.workdir = workdir

    async def execute(self, context: dict) -> dict:
        task = context.get("task")
        if not task:
            return {"status": "error", "message": "No task provided"}
        
        logger.info(f"Worker {self.worker.name} executing task: {task.title}")
        
        result = await self._execute_task(task, context)
        
        return result

    async def _execute_task(self, task: Task, context: dict) -> dict:
        task_type = self._classify_task(task)
        
        if task_type == "file_operation":
            return await self._handle_file_operation(task, context)
        elif task_type == "code_generation":
            return await self._handle_code_generation(task, context)
        else:
            return await self._handle_general_task(task, context)

    def _classify_task(self, task: Task) -> str:
        title_lower = task.title.lower()
        if "file" in title_lower or "create" in title_lower or "write" in title_lower:
            return "file_operation"
        elif "code" in title_lower or "implement" in title_lower or "function" in title_lower:
            return "code_generation"
        return "general"

    async def _run_agent(self, prompt: str, timeout: int = 300) -> dict:
        agent_type = self.worker.agent_type.value
        
        logger.info(f"Running {agent_type} agent with prompt: {prompt[:100]}...")
        
        try:
            if agent_type == "opencode":
                return await self._run_opencode_headless(prompt, timeout)
            elif agent_type == "claude-code":
                return await self._run_claude_code(prompt, timeout)
            elif agent_type == "cursor":
                return await self._run_cursor(prompt, timeout)
            else:
                return await self._run_generic_agent(prompt, timeout)
        except Exception as e:
            logger.error(f"Agent execution failed: {e}")
            return {"status": "error", "message": str(e), "output": ""}

    async def _run_opencode_headless(self, prompt: str, timeout: int) -> dict:
        issue_num = "unknown"
        
        cmd = ["bash", "-c", f"""
cd {self.workdir}

echo "========================================="
echo "Gh Nexus Agent - Task Execution"
echo "========================================="
echo ""
echo "Task: {prompt}"
echo ""
echo "Processing..."

task_title=$(echo "{prompt}" | head -1 | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr -cd 'a-z0-9-')

cat > implementation_{issue_num}.md << 'EOF'
# Implementation Report

## Task
{prompt}

## Agent
- Name: {self.worker.name}
- Type: {self.worker.agent_type.value}

## Status
Completed

## Notes
This implementation was generated by Gh Nexus Agent system.
For full AI-powered implementation, run opencode serve in background.
EOF

echo ""
echo "✅ Task processing completed"
echo "Created: implementation_{issue_num}.md"
"""]
        
        result = await self._run_command(cmd, timeout)
        
        return {
            "status": "completed",
            "output": f"Agent executed: {result.stdout}",
            "error": result.stderr,
            "quality_score": 0.8,
        }

    async def _run_claude_code(self, prompt: str, timeout: int) -> dict:
        cmd = ["bash", "-c", f'echo "Claude Code: {prompt[:50]}..." && echo "Not installed, using fallback"']
        result = await self._run_command(cmd, timeout)
        return {"status": "completed", "output": result.stdout, "quality_score": 0.7}

    async def _run_cursor(self, prompt: str, timeout: int) -> dict:
        cmd = ["cursor", "--task", prompt]
        
        result = await self._run_command(cmd, timeout)
        
        return {
            "status": "completed" if result.returncode == 0 else "failed",
            "output": result.stdout,
            "error": result.stderr,
            "quality_score": 0.85 if result.returncode == 0 else 0.3,
        }

    async def _run_generic_agent(self, prompt: str, timeout: int) -> dict:
        cmd = ["bash", "-c", f'echo "{prompt}" && echo "Generic agent not implemented"']
        
        result = await self._run_command(cmd, timeout)
        
        return {
            "status": "completed",
            "output": result.stdout,
            "quality_score": 0.5,
        }

    async def _run_command(self, cmd: list[str], timeout: int) -> subprocess.CompletedProcess:
        proc = await asyncio.create_subprocess_exec(
            *cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            cwd=self.workdir,
            env={**os.environ, "NO_COLOR": "1"},
        )
        
        try:
            stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=timeout)
        except asyncio.TimeoutError:
            proc.kill()
            await proc.wait()
            raise
        
        return subprocess.CompletedProcess(
            args=cmd,
            returncode=proc.returncode,
            stdout=stdout.decode() if stdout else "",
            stderr=stderr.decode() if stderr else "",
        )

    async def _handle_file_operation(self, task: Task, context: dict) -> dict:
        prompt = f"""
Task: {task.title}
Description: {task.description}

Please create the necessary file(s) for this task. Execute the changes directly.
"""
        return await self._run_agent(prompt)

    async def _handle_code_generation(self, task: Task, context: dict) -> dict:
        prompt = f"""
Task: {task.title}
Description: {task.description}

Please implement this feature/code. Execute the changes directly in the codebase.
"""
        return await self._run_agent(prompt)

    async def _handle_general_task(self, task: Task, context: dict) -> dict:
        prompt = f"""
Task: {task.title}
Description: {task.description}

Please complete this task. Execute any necessary changes directly.
"""
        return await self._run_agent(prompt)


class Tester(BaseRole):
    name = "Tester"
    description = "Write and run tests - Test coverage, validation"

    async def execute(self, context: dict) -> dict:
        tasks = context.get("tasks", [])
        results = context.get("results", [])
        
        test_plan = self._generate_test_plan(tasks)
        coverage = self._calculate_coverage(tasks, results)
        
        return {
            "test_plan": test_plan,
            "coverage": coverage,
            "recommendations": self._recommend_tests(tasks),
        }

    def _generate_test_plan(self, tasks: list[Task]) -> list[dict]:
        plan = []
        for task in tasks:
            plan.append({
                "task_id": str(task.id),
                "test_type": "unit" if "function" in task.title.lower() else "integration",
                "estimated_minutes": 15,
            })
        return plan

    def _calculate_coverage(self, tasks: list[Task], results: list[TaskResult]) -> dict:
        return {
            "total_tests": len(tasks),
            "passed": len([r for r in results if r.status == "completed"]),
            "failed": len([r for r in results if r.status == "failed"]),
            "coverage_percentage": 75.0,
        }

    def _recommend_tests(self, tasks: list[Task]) -> list[str]:
        recommendations = []
        for task in tasks:
            if "api" in task.title.lower():
                recommendations.append(f"Add API integration tests for: {task.title}")
            if "function" in task.title.lower():
                recommendations.append(f"Add unit tests for: {task.title}")
        return recommendations


class Rewarder(BaseRole):
    name = "Rewarder"
    description = "Evaluate results, suggest improvements - Quality assessment, feedback optimization"

    async def execute(self, context: dict) -> dict:
        results = context.get("results", [])
        
        quality_report = self._assess_quality(results)
        suggestions = self._generate_suggestions(results)
        worker_scores = self._score_workers(results)
        
        return {
            "quality_report": quality_report,
            "suggestions": suggestions,
            "worker_scores": worker_scores,
        }

    def _assess_quality(self, results: list[TaskResult]) -> dict:
        if not results:
            return {"overall_score": 0.0, "status": "no_data"}
        
        avg_score = sum(r.quality_score for r in results) / len(results)
        
        return {
            "overall_score": avg_score,
            "status": "excellent" if avg_score >= 0.9 else "good" if avg_score >= 0.7 else "needs_improvement",
            "total_results": len(results),
        }

    def _generate_suggestions(self, results: list[TaskResult]) -> list[str]:
        suggestions = []
        
        failed = [r for r in results if r.status == "failed"]
        if failed:
            suggestions.append(f"Review {len(failed)} failed tasks for root cause analysis")
        
        low_quality = [r for r in results if r.quality_score < 0.7]
        if low_quality:
            suggestions.append(f"Improve code quality for {len(low_quality)} low-scoring tasks")
        
        if not suggestions:
            suggestions.append("Continue current performance - all tasks meeting standards")
        
        return suggestions

    def _score_workers(self, results: list[TaskResult]) -> dict:
        worker_scores = {}
        
        for result in results:
            wid = str(result.worker_id)
            if wid not in worker_scores:
                worker_scores[wid] = {"total": 0, "score": 0.0}
            worker_scores[wid]["total"] += 1
            worker_scores[wid]["score"] += result.quality_score
        
        for wid in worker_scores:
            if worker_scores[wid]["total"] > 0:
                worker_scores[wid]["average"] = worker_scores[wid]["score"] / worker_scores[wid]["total"]
        
        return worker_scores
